# Generated by Django 5.0.6 on 2024-07-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_total_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
